### ISSUE TITLE
Test the Android beta!

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trolley-tracker-android-client#1]
Went ahead and published the app as a beta on the play store. Needs a good bit of work (and I already know of one bug where the app crashes) but I figured people would want to try it out at our meeting tomorrow (8/25).

Here's the link to opt-in and download: https://play.google.com/apps/testing/com.codeforgvl.trolleytrackerclient

**Comment by ajhodges** [comment]
@agautsc

**Comment by jeremywight** [comment]
It says Not Found in play store for new after registering

**Comment by ajhodges** [comment]
@jeremywight I'm getting that error too in Chrome, try opening the link from your phone, it should redirect you to the play store page

**Comment by ajhodges** [comment]
Actually I think the issue was probably that you're logged in as yeahthattrolley@gmail.com in the play store browser. I just noticed that. Added that user to the beta and it works now.
