### ISSUE TITLE
Show direction of trolley in UI

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trolley-tracker-android-client#16]
Use the last x number of trolley updates to determine the trolley's direction. Maybe show the direction the trolley is travelling when the trolley is selected.

**Comment by bikeoid** [comment]
@Linktheoriginal made a suggestion for the travel direction indicator to come from the server.  That would eliminate the need for 3 clients to individually code this.   The only question to decide is if we want to increase the message size for every client update, or is this only an occasional query if they select the trolley (that would be a delayed response though).

**Comment by ajhodges** [comment]
I think the message size is pretty small, direction probably wouldn't
haven't have a big impact on our message size. I'm not too worried about
burning through our users' bandwidth. It's probably being used in bursts. I
doubt the tracker app is being used more than 30 seconds at a time or so.
But also it wouldn't take much effort to determine direction on the client
side. Your call.
