### ISSUE TITLE
Feedback button

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trolley-tracker-android-client#23]
Button that opens email app to leave feedback

**Comment by agautsc** [comment]
@ajhodges I updated the Play Store email to yeahthatrolley+@gmail.com and make it so +1 also forwards to you. You should get an email verification. Can you send me that info.

**Comment by ajhodges** [comment]
I think I have verified the forwarding. Thanks! I'll also use that address
for the in-app feedback button when I get around to it

**Comment by divpatel10** [comment]
Hi @ajhodges , I have implemented a feedback button in the trolley_tracker_div branch if you want to check it out.
