### ISSUE TITLE
Copy for Play Store Listing

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trolley-tracker-android-client#3]
Need logos, screenshots, a 'feature image', app name, app description for the play store listing.

**Comment by agautsc** [comment]
:hand:

**Comment by agautsc** [comment]
Updated logo, banner image, and long description submitted and waiting approval.

**Comment by agautsc** [comment]
The content updates went live https://play.google.com/store/apps/details?id=com.codeforgvl.trolleytrackerclient Please review and let me know if they make sense and read right to everyone. 

I did add the http:// to the YeahThatTrolley.com URL. That might not show up yet.
