### ISSUE TITLE
Trolley schedule not showing up

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trolley-tracker-android-client#38]
The trolley schedule isn't showing at the moment on my phone, but it shows up in the webapp just fine.

**Comment by jeremywight** [comment]
Odd. It's working on the iOS app. I'll check my Nexus a bit later

**Comment by ajhodges** [comment]
Showing up on my phone now... weird... might have had something to do with
my connection at work.. still worth investigating!
