### ISSUE TITLE
Routing/ETA (User -> Stop, Trolleys -> User)

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trolley-tracker-android-client#4]
There are web services that can be used to accomplish this, for example the Google Distance Matrix API, MapQuest RouteMatrix, Bing Route Data. Need to investigate API limitations...

More interestingly, there is an offline solution called graphhopper: https://github.com/graphhopper/graphhopper/blob/0.5/docs/android/index.md

I'm thinking that the OSM data for Greenville will be small enough to package in to the app and search without a huge performance hit. Will need to test on a crappy phone to confirm.

**Comment by bikeoid** [comment]
In  this area, there is http://trip.greenvilleopenmap.info/opentripplanner-webapp/#/ without an API limitation, but not always speedy.

There's also rrrr , optimized for local usage Smartphone devices  https://github.com/bliksemlabs/rrrr/tree/tdata4  - not sure which branch is best. (Great for Navigate like a Pirate day)

**Comment by ajhodges** [comment]
Thanks! That is very helpful. I'll have to look in to this stuff. From a simplicity standpoint, we might should just do the Google API with a failover to the opentripplanner service. But it would definitely up the coolness factor if we could do the routing locally

**Comment by ajhodges** [comment]
Implementing algorithm described in: https://github.com/codeforgreenville/trolley-tracker-api-dot-net/issues/7
