### ISSUE TITLE
Null pointer exception while previewing route

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trolley-tracker-android-client#41]
![image](https://cloud.githubusercontent.com/assets/856738/23373351/a1a68ef6-fced-11e6-98df-18874912a85f.png)

I think this probably ties in with #17. Seems like the call to the API came back with null. Need better exception handling.

**Comment by stampthecoder** [comment]
I believe I have a fix for this. I will test this week when I get a chance.

**Comment by divpatel10** [comment]
I think it occurred only when there was no internet connection. I have added a condition to only preview route when internet connection is available.
