### ISSUE TITLE
Improve UI when reloading app

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trolley-tracker-android-client#49]
The changes we made in #42 have made it so the routes are not cached by the client, so depending on the Android lifecycle, sometimes when you open the app after it has been in the background for some time the map will be blank for a few seconds while it reloads.

The original behavior was that the old version of the trolleys/routes were shown and then it updated as soon as the new data was available. I think we should either try to find a way to preserve this while avoiding #42 or come up with a good loading indicator to show the users that the latest route/trolley data is being pulled.

**Comment by bikeoid** [comment]
This would be a good addition.   I didn't know how to trigger all the Android life cycles to show this condition   In my case, I was seeing the Splash screen from restart and didn't realize that it wouldn't show in some cases.
