### ISSUE TITLE
Schedule View Not Responsive

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker-android-client#50]
Was just doing some testing on the production app and it appears that the Schedule page is not responsive (Pixel 1)

**Comment by ajhodges** [comment]
Interesting. Not working for me either. Not sure what could have changed, I will check into this. Site note, the web app isn't working for me right now: http://trackthetrolley.com/greenville-sc-trolley/

**Comment by Linktheoriginal** [comment]
Did the API change?  I haven't looked at this in forever, but I have a reference to http://api.yeahthattrolley.com/api/v1/RouteSchedules that's failing. @bikeoid, you've been working on converting it out of django, maybe it's time to switch to your version?

**Comment by bikeoid** [comment]
That API change was unintentional, I'll have to look at that.   I'm guess that it's what is causing the Android schedule view to fail also.      I'll go ahead and switch the web site to use the web client from the main API server - it looks like this on the Dev server - http://yeahthattrolley.azurewebsites.net/ClientWeb

**Comment by ajhodges** [comment]
Phew... thanks @bikeoid! Looks like it's working now. Fixed with https://github.com/codeforgreenville/trolley-tracker-api-dot-net/issues/41 

Hoping to spend some time over the next month updating the app to bring it up to date with the latest and greatest API changes.
