### ISSUE TITLE
Drivers using the consumer app

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker-android-client#9]
One the drivers suggested that they use the consumer app to see where the other trolley is so they can better time the driving and we don't get into the situation where two trolleys are basically following each other around the loop.

Seems like a pretty good idea. The one question Greenlink had was, "how much data would be used if they kept the app running for an entire day."

The other thing was we'd have to change the app to keep the device screen on at all times. A positive for this would be that we at least know the device would be on.

Any other thoughts? 

CC: @ajhodges

**Comment by ajhodges** [comment]
I'd have to make the app tablet friendly, but I think that should be done anyways.

As far as data goes, it should really be minimal. I'm estimating ~90kb/hr, which would be 0.72Mb if the trolley was left on for 8 hours.

As for keeping the screen on, that's about 1 line of code. The question is if we want to include that feature in the general version of the client, or limit it to the trolleys? I think that might be a good feature to include, just wanted to open up discussion about it.

**Comment by jeremywight** [comment]
Yeah I don’t know that I’d want the app forcing my phone to stay awake indefinitely if it were running on my phone.

**Comment by ajhodges** [comment]
It's not necessarily that it forces it to stay awake, it just disables the screen sleep timeout. If you press the power button, it would still turn off. And you can switch apps and the screen sleep timeout works normally.

I think Google Maps does this if you want to see what I mean.

**Comment by agautsc** [comment]
My thought was to have second app, but if we think through it there might be a good way to do it with one app. I think the Google Maps only stays on if plugged in or at least prompt to dim the screen if not plugged in. That might be a good way to handle the issue.
